/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

var inherits = require('inherits');

var kurentoClient = require('kurento-client');

var ChecktypeError = kurentoClient.checkType.ChecktypeError;

var MediaElement = require('./MediaElement');

/**
 * @classdesc
 *  Base interface for all filters. This is a certain type of {@link module:core/abstracts.MediaElement MediaElement}, that processes media injected through its sinks, and delivers the outcome through its sources.
 *
 * @abstract
 * @extends module:core/abstracts.MediaElement
 *
 * @constructor module:core/abstracts.Filter
 */
function Filter(){
  Filter.super_.call(this);
};
inherits(Filter, MediaElement);

/**
 * @alias module:core/abstracts.Filter.constructorParams
 */
Filter.constructorParams = {};

/**
 * @alias module:core/abstracts.Filter.events
 *
 * @extend module:core/abstracts.MediaElement.events
 */
Filter.events = MediaElement.events;

module.exports = Filter;

Filter.check = function(key, value)
{
  if(!(value instanceof Filter))
    throw ChecktypeError(key, Filter, value);
};
