/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

var inherits = require('inherits');


/**
 * Media API for the Kurento Web SDK
 *
 * @module core/abstracts
 *
 * @copyright 2013-2014 Kurento (http://kurento.org/)
 * @license LGPL
 */

var MediaElement = require('./MediaElement');


/**
 * Base interface for all filters. This is a certain type of {@link MediaElement}, that processes media injected through its {@link MediaSink}, and delivers the outcome through its {@link MediaSource}.
 *
 * @abstract
 * @class module:core/abstracts.Filter
 * @extends module:core/abstracts.MediaElement
 */

/**
 * @constructor
 *
 * @param {string} id
 */
function Filter(id){
  MediaElement.call(this, id);
};
inherits(Filter, MediaElement);


/**
 * @type module:core/abstracts.Filter.constructorParams
 */
Filter.constructorParams = {};

/**
 * @type module:core/abstracts.Filter.events
 *
 * @extend module:core/abstracts.MediaElement.events
 */
Filter.events = [];
Filter.events.concat(MediaElement.events);


module.exports = Filter;


Filter.check = function(key, value)
{
  if(!(value instanceof Filter))
    throw SyntaxError(key+' param should be a Filter, not '+typeof value);
};
