/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

var inherits = require('inherits');

var checkType = require('checktype');


/**
 * Media API for the Kurento Web SDK
 *
 * @module core/abstracts
 *
 * @copyright 2013-2014 Kurento (http://kurento.org/)
 * @license LGPL
 */

var MediaPad = require('./MediaPad');


/**
 * Special type of pad, used by a {@link MediaElement} to receive a media stream.
 *
 * @abstract
 * @class module:core/abstracts.MediaSink
 * @extends module:core/abstracts.MediaPad
 */

/**
 * @constructor
 *
 * @param {string} id
 */
function MediaSink(id){
  MediaPad.call(this, id);
};
inherits(MediaSink, MediaPad);


/**
 * Disconnects the current sink from the referred {@link MediaSource}
 *
 * @param {MediaSource} src
 *  The source to disconnect
 *
 * @param {module:core/abstracts.MediaSink~disconnectCallback} [callback]
 *
 * @return {external:Promise}
 */
MediaSink.prototype.disconnect = function(src, callback){
  checkType('MediaSource', 'src', src, {required: true});

  var params = {
    src: src,
  };

  return this.invoke('disconnect', params, callback);
};
/**
 * @callback module:core/abstracts.MediaSink~disconnectCallback
 * @param {Error} error
 */

/**
 * Gets the {@link MediaSource} that is connected to this sink.
 *
 * @param {module:core/abstracts.MediaSink~getConnectedSrcCallback} [callback]
 *
 * @return {external:Promise}
 */
MediaSink.prototype.getConnectedSrc = function(callback){
  return this.invoke('getConnectedSrc', callback);
};
/**
 * @callback module:core/abstracts.MediaSink~getConnectedSrcCallback
 * @param {Error} error
 * @param {MediaSource} result
 *  The source connected to this sink
 */


/**
 * @type module:core/abstracts.MediaSink.constructorParams
 */
MediaSink.constructorParams = {};

/**
 * @type module:core/abstracts.MediaSink.events
 *
 * @extend module:core/abstracts.MediaPad.events
 */
MediaSink.events = [];
MediaSink.events.concat(MediaPad.events);


module.exports = MediaSink;


MediaSink.check = function(key, value)
{
  if(!(value instanceof MediaSink))
    throw SyntaxError(key+' param should be a MediaSink, not '+typeof value);
};
