/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

var inherits = require('inherits');

var checkType = require('checktype');



var MediaPad = require('./MediaPad');


/**
 * @classdesc
 *  Special type of pad, used by a media element to generate a media stream.
 *
 * @abstract
 * @extends module:core/abstracts.MediaPad
 *
 * @constructor module:core/abstracts.MediaSource
 *
 * @param {string} id
 */
function MediaSource(id){
  MediaPad.call(this, id);
};
inherits(MediaSource, MediaPad);


/**
 * Connects the current source with a {@link MediaSink}
 *
 * @alias module:core/abstracts.MediaSource.connect
 *
 * @param {MediaSink} sink
 *  The sink to connect this source
 *
 * @param {module:core/abstracts.MediaSource~connectCallback} [callback]
 *
 * @return {external:Promise}
 */
MediaSource.prototype.connect = function(sink, callback){
  checkType('MediaSink', 'sink', sink, {required: true});

  var params = {
    sink: sink,
  };

  return this.invoke('connect', params, callback);
};
/**
 * @callback module:core/abstracts.MediaSource~connectCallback
 * @param {Error} error
 */

/**
 * Gets all the {@link MediaSink MediaSinks} to which this source is connected
 *
 * @param {module:core/abstracts.MediaSource~getConnectedSinksCallback} [callback]
 *
 * @return {external:Promise}
 */
MediaSource.prototype.getConnectedSinks = function(callback){
  return this.invoke('getConnectedSinks', callback);
};
/**
 * @callback module:core/abstracts.MediaSource~getConnectedSinksCallback
 * @param {Error} error
 * @param {MediaSink} result
 *  the list of sinks that the source is connected to
 */


/**
 * Disconnect this source pad from the specified sink pad
 *
 * @public
 *
 * @param {...module:core/abstract.MediaSink} sink - Sink to be disconnected
 * @param {module:core/abstract.MediaSource~disconnectCallback} callback
 *
 * @return {external:Promise}
 */
MediaSource.prototype.disconnect = function(sink, callback){
  checkType('MediaSink', 'sink', sink, {required: true});

  var params =
  {
    src: this
  };

  return sink.invoke('disconnect', params, callback);
};
/**
 * @callback module:core/abstract.MediaSource~disconnectCallback
 * @param {external:Error} error
 */


/**
 * @alias module:core/abstracts.MediaSource.constructorParams
 */
MediaSource.constructorParams = {};

/**
 * @alias module:core/abstracts.MediaSource.events
 *
 * @extend module:core/abstracts.MediaPad.events
 */
MediaSource.events = [];
MediaSource.events.concat(MediaPad.events);


module.exports = MediaSource;


MediaSource.check = function(key, value)
{
  if(!(value instanceof MediaSource))
    throw SyntaxError(key+' param should be a MediaSource, not '+typeof value);
};
