/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

var inherits = require('inherits');

var checkType = require('checktype');


/**
 * Media API for the Kurento Web SDK
 *
 * @module core/abstracts
 *
 * @copyright 2013-2014 Kurento (http://kurento.org/)
 * @license LGPL
 */

var Endpoint = require('./Endpoint');


/**
 * Interface for endpoints the require a URI to work. An example of this, would be a {@link PlayerEndpoint} whose URI property could be used to locate a file to stream through its {@link MediaSource}
 *
 * @abstract
 * @class module:core/abstracts.UriEndpoint
 * @extends module:core/abstracts.Endpoint
 */

/**
 * @constructor
 *
 * @param {string} id
 */
function UriEndpoint(id){
  Endpoint.call(this, id);
};
inherits(UriEndpoint, Endpoint);


/**
 * The uri for this endpoint.
 *
 * @param {module:core/abstracts.UriEndpoint~getUriCallback} [callback]
 *
 * @return {external:Promise}
 */
UriEndpoint.prototype.getUri = function(callback){
  return this.invoke('getUri', callback);
};
/**
 * @callback module:core/abstracts.UriEndpoint~getUriCallback
 * @param {Error} error
 * @param {String} result
 */


/**
 * Pauses the feed
 *
 * @param {module:core/abstracts.UriEndpoint~pauseCallback} [callback]
 *
 * @return {external:Promise}
 */
UriEndpoint.prototype.pause = function(callback){
  return this.invoke('pause', callback);
};
/**
 * @callback module:core/abstracts.UriEndpoint~pauseCallback
 * @param {Error} error
 */

/**
 * Stops the feed
 *
 * @param {module:core/abstracts.UriEndpoint~stopCallback} [callback]
 *
 * @return {external:Promise}
 */
UriEndpoint.prototype.stop = function(callback){
  return this.invoke('stop', callback);
};
/**
 * @callback module:core/abstracts.UriEndpoint~stopCallback
 * @param {Error} error
 */


/**
 * @type module:core/abstracts.UriEndpoint.constructorParams
 */
UriEndpoint.constructorParams = {};

/**
 * @type module:core/abstracts.UriEndpoint.events
 *
 * @extend module:core/abstracts.Endpoint.events
 */
UriEndpoint.events = [];
UriEndpoint.events.concat(Endpoint.events);


module.exports = UriEndpoint;


UriEndpoint.check = function(key, value)
{
  if(!(value instanceof UriEndpoint))
    throw SyntaxError(key+' param should be a UriEndpoint, not '+typeof value);
};
