/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

/**
 * Media API for the Kurento Web SDK
 *
 * @module core/complexTypes
 *
 * @copyright 2013-2014 Kurento (http://kurento.org/)
 * @license LGPL
 */

var AudioCaps = require('./AudioCaps');
var AudioCodec = require('./AudioCodec');
var ElementConnectionData = require('./ElementConnectionData');
var FilterType = require('./FilterType');
var Fraction = require('./Fraction');
var MediaType = require('./MediaType');
var ModuleInfo = require('./ModuleInfo');
var ServerInfo = require('./ServerInfo');
var ServerType = require('./ServerType');
var VideoCaps = require('./VideoCaps');
var VideoCodec = require('./VideoCodec');


exports.AudioCaps = AudioCaps;
exports.AudioCodec = AudioCodec;
exports.ElementConnectionData = ElementConnectionData;
exports.FilterType = FilterType;
exports.Fraction = Fraction;
exports.MediaType = MediaType;
exports.ModuleInfo = ModuleInfo;
exports.ServerInfo = ServerInfo;
exports.ServerType = ServerType;
exports.VideoCaps = VideoCaps;
exports.VideoCodec = VideoCodec;
