/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials are made
 * available under the terms of the GNU Lesser General Public License (LGPL)
 * version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

var inherits = require('inherits');

var kurentoClient = require('kurento-client');

var checkType = kurentoClient.checkType;
var ChecktypeError = checkType.ChecktypeError;

var ComplexType = require('./ComplexType');


/**
 * A dictionary that represents the stats gathered.
 *
 * @constructor module:core/complexTypes.MediaLatencyStat
 *
 * @property {external:String} name
 *  The identifier of the media stream
 * @property {module:core/complexTypes.MediaType} type
 *  Type of media stream
 * @property {external:double} avg
 *  The average time that buffers take to get on the input pad of this element
 */
function MediaLatencyStat(mediaLatencyStatDict){
  if(!(this instanceof MediaLatencyStat))
    return new MediaLatencyStat(mediaLatencyStatDict)

  mediaLatencyStatDict = mediaLatencyStatDict || {}

  // Check mediaLatencyStatDict has the required fields
  checkType('String', 'mediaLatencyStatDict.name', mediaLatencyStatDict.name, {required: true});
  checkType('MediaType', 'mediaLatencyStatDict.type', mediaLatencyStatDict.type, {required: true});
  checkType('double', 'mediaLatencyStatDict.avg', mediaLatencyStatDict.avg, {required: true});

  // Init parent class
  MediaLatencyStat.super_.call(this, mediaLatencyStatDict)

  // Set object properties
  Object.defineProperties(this, {
    name: {
      writable: true,
      enumerable: true,
      value: mediaLatencyStatDict.name
    },
    type: {
      writable: true,
      enumerable: true,
      value: mediaLatencyStatDict.type
    },
    avg: {
      writable: true,
      enumerable: true,
      value: mediaLatencyStatDict.avg
    }
  })
}
inherits(MediaLatencyStat, ComplexType)

// Private identifiers to allow re-construction of the complexType on the server
// They need to be enumerable so JSON.stringify() can access to them
Object.defineProperties(MediaLatencyStat.prototype, {
  __module__: {
    enumerable: true,
    value: "kurento"
  },
  __type__: {
    enumerable: true,
    value: "MediaLatencyStat"
  }
})

/**
 * Checker for {@link module:core/complexTypes.MediaLatencyStat}
 *
 * @memberof module:core/complexTypes
 *
 * @param {external:String} key
 * @param {module:core/complexTypes.MediaLatencyStat} value
 */
function checkMediaLatencyStat(key, value)
{
  if(!(value instanceof MediaLatencyStat))
    throw ChecktypeError(key, MediaLatencyStat, value);
};


module.exports = MediaLatencyStat;

MediaLatencyStat.check = checkMediaLatencyStat;
