/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

var checkType = require('kurento-client').checkType;

/**
 * Checker for {@link core/complexTypes.RTCIceCandidateAttributes}
 *
 * @memberof module:core/complexTypes
 *
 * @param {external:String} key
 * @param {module:core/complexTypes.RTCIceCandidateAttributes} value
 */
function checkRTCIceCandidateAttributes(key, value)
{
  checkType('String', key+'.ipAddress', value.ipAddress, true);
  checkType('int', key+'.portNumber', value.portNumber, true);
  checkType('String', key+'.transport', value.transport, true);
  checkType('RTCStatsIceCandidateType', key+'.candidateType', value.candidateType, true);
  checkType('int', key+'.priority', value.priority, true);
  checkType('String', key+'.addressSourceUrl', value.addressSourceUrl, true);
};


/**
 * 
 *
 * @memberof module:core/complexTypes
 *
 * @typedef core/complexTypes.RTCIceCandidateAttributes
 *
 * @type {Object}
 * @property {external:String} ipAddress
 *  It is the IP address of the candidate, allowing for IPv4 addresses, IPv6 addresses, and fully qualified domain names (FQDNs).
 * @property {external:Integer} portNumber
 *  It is the port number of the candidate.
 * @property {external:String} transport
 *  Valid values for transport is one of udp and tcp. Based on the 'transport' defined in [RFC5245] section 15.1.
 * @property {module:core/complexTypes.RTCStatsIceCandidateType} candidateType
 *  The enumeration RTCStatsIceCandidateType is based on the cand-type defined in [RFC5245] section 15.1.
 * @property {external:Integer} priority
 *  Represents the priority of the candidate
 * @property {external:String} addressSourceUrl
 *  The URL of the TURN or STUN server indicated in the RTCIceServers that translated this IP address.
 */


module.exports = checkRTCIceCandidateAttributes;
