/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

var checkType = require('kurento-client').checkType;

/**
 * Checker for {@link core/complexTypes.RTCPeerConnectionStats}
 *
 * @memberof module:core/complexTypes
 *
 * @param {external:String} key
 * @param {module:core/complexTypes.RTCPeerConnectionStats} value
 */
function checkRTCPeerConnectionStats(key, value)
{
  checkType('int', key+'.dataChannelsOpened', value.dataChannelsOpened, true);
  checkType('int', key+'.dataChannelsClosed', value.dataChannelsClosed, true);
};


/**
 * Statistics related to the peer connection.
 *
 * @memberof module:core/complexTypes
 *
 * @typedef core/complexTypes.RTCPeerConnectionStats
 *
 * @type {Object}
 * @property {external:Integer} dataChannelsOpened
 *  Represents the number of unique datachannels opened.
 * @property {external:Integer} dataChannelsClosed
 *  Represents the number of unique datachannels closed.
 */


module.exports = checkRTCPeerConnectionStats;
