/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */


/**
 * An error related to the MediaObject has occurred
 *
 * @event module:core#Error
 *
 * @property {module:core/abstracts.MediaObject} object
 *  {@link module:core/abstracts.MediaObject MediaObject} where the error originated
 * @property {external:String} description
 *  Textual description of the error
 * @property {external:Integer} errorCode
 *  Server side integer error code
 * @property {external:String} type
 *  Integer code as a String
 */

/**
 * Base for all events raised by elements in the Kurento media server.
 *
 * @event module:core#Media
 *
 * @property {module:core/abstracts.MediaObject} source
 *  Object that raised the event
 * @property {external:String} type
 *  Type of event that was raised
 */

/**
 * Event raised when a session starts. This event has no data.
 *
 * @event module:core#MediaSessionStarted
 */

/**
 * Event raised when a session is terminated. This event has no data.
 *
 * @event module:core#MediaSessionTerminated
 */

/**
 * Indicates that an object has been created on the mediaserver
 *
 * @event module:core#ObjectCreated
 *
 * @property {module:core/abstracts.MediaObject} object
 *  The object that has been created
 */

/**
 * Indicates that an object has been destroyed on the mediaserver
 *
 * @event module:core#ObjectDestroyed
 *
 * @property {external:String} objectId
 *  The id of the object that has been destroyed
 */
